### ISSUE TITLE
Make Server-Switcher Firefox extension compartable with miltiprocess (e10s)

### ISSUE THREAD

**Issue by MurzNN** [Bronkoknorb/Server-Switcher#8]
Extension is very useful, but on new Firefox versions it shows as incompatible with miltiprocess (e10s). Can you make it compatible for enable miltiprocess on Firefox? Thanks!

**Comment by knobhead** [comment]
Or, in fact, turn it into a web extension? This extension is far too useful to go down the drain when Firefox 57 comes upon us :(

**Comment by Bronkoknorb** [comment]
Sorry, I do not have time to work on this extension any more. But it is open-source and contributors are welcome of course!

**Comment by MurzNN** [comment]
For other who searching the solution - I have found alternative extension with same functional: https://addons.mozilla.org/en-US/firefox/addon/location-switcher/?src=search
